### ISSUE TITLE
Allow inheritance of Compiled* classes by configuration

### ISSUE THREAD

**Issue by timoschmidt** [webforge-labs/webforge-doctrine-compiler#35]
When using thridparty libaries, like FOSUsers it is quit handy to have the possibility to configure a class where the Compile class should inherit from. Besided that, the constructor of the parent class should be called in the constructor of the Compiled* class.

**Comment by pscheit** [comment]
hey,

use
```json
"name": "MyEntity",
"extends": "FOS\\Entity\\User",
...
```
for that

**Comment by timoschmidt** [comment]
Ach cool :)
